-- Review before running. This starter expects visitor_logs to be dedicated to this tracker.
-- If you already have a shared visitor_logs table, reconcile column names and policies first.

create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  domain text not null,
  visitor_type text not null check (visitor_type in ('human','bot')),
  page_path text,
  referrer text,
  user_agent text,
  timestamp timestamptz not null default now()
);

alter table public.visitor_logs add column if not exists page_path text;
alter table public.visitor_logs enable row level security;

-- Anonymous visitors may INSERT only. They cannot read or delete visitor records.
drop policy if exists "public can insert vehikal visitor events" on public.visitor_logs;
create policy "public can insert vehikal visitor events"
on public.visitor_logs for insert to anon
with check (
  domain = 'vehikal.com'
  and visitor_type in ('human','bot')
);

-- Signed-in users can read Vehikal records. Create dashboard accounts only for trusted admins.
drop policy if exists "authenticated admins can read vehikal visitor events" on public.visitor_logs;
create policy "authenticated admins can read vehikal visitor events"
on public.visitor_logs for select to authenticated
using (domain = 'vehikal.com');

-- Only authenticated admins can delete Vehikal.com rows.
drop policy if exists "authenticated admins can delete vehikal visitor events" on public.visitor_logs;
create policy "authenticated admins can delete vehikal visitor events"
on public.visitor_logs for delete to authenticated
using (domain = 'vehikal.com');

-- Reset is restricted to authenticated users and only deletes Vehikal.com rows.
create or replace function public.reset_vehikal_visitor_logs()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  delete from public.visitor_logs
  where domain = 'vehikal.com';
end;
$$;

revoke all on function public.reset_vehikal_visitor_logs() from public;
grant execute on function public.reset_vehikal_visitor_logs() to authenticated;

-- Restrict browser access to only required operations.
grant insert on public.visitor_logs to anon;
grant select, delete on public.visitor_logs to authenticated;
